# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:
-jekyll-paginate
-jekyll-sitemap
-jekyll-feed
-jekyll-seo-tag
-jekyll-include-cache
-jektify

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Dan Peluso"
description:	       "A collection of projects"
author:              "Daniel Peluso"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml





jektify:
  enable: true
  open: false
  toggle:
    enable: true
  spotify:
    user: pelusodan
    text: Hide
  sass:
    jekyll: true
    other:
      dir: "way/to/your/SASS"
  title:
    enable: true
    text: "Jektify"
  description:
    enable: true
    text: |
      Jekyll plugin to generate html snippets for embedding Spotify Musics.
      To listen to the full song, open your Spotify and start these musics.
