# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Philanthropy', folder: 'pages', file: 'philanthropy.html'}
- {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Resume', folder: 'pages', file: 'resume.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/daniel.peluso.370'}
- {icon: 'instagram', link: 'https://www.instagram.com/pelusodan/'}
- {icon: 'envelope', link: 'mailto:pelusodan@gmail.com'}
- {icon: 'linkedin', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
